Home/urls.py
from django.urls import path
from .views import home_view

app_name = 'Home'
urlpatterns = [
    path('', home_view, name='HomeView'),

]

blog/urls.py
from django.urls import path
from .views import blog_list_view, BlogDetailView, CommentCreatView, delete_blog_view, update_blog, add_blog
app_name = 'blog'
urlpatterns = [
    path('', blog_list_view, name='blog_list'),
    path('<int:pk>', BlogDetailView.as_view(), name='blog_detail'),
    path('<int:id>/comment', CommentCreatView.as_view(), name='comment_create'),
    path('update/<int:pk>', update_blog, name='update_blog'),
    path('delete/<int:blog_id>', delete_blog_view, name='delete_blog'),
    path('add_blog', add_blog, name='add_blog'),


]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('blog', include('blog.urls')),
    path('', include('Home.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('favorite/', include('favorite.urls')),
    path('contact/', include('contact.urls')),
    path('ticket/', include('tickets.uels')),


    # path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from accounts.models import User
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget


class Blogs(models.Model):
    title = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(null=True)
    cover = models.ImageField(upload_to='blogs/', null=True)
    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_modified = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField()

    def __str__(self):
        return self.title
    

    def get_absolute_url(self):
        return reverse('blog_detail', args=[self.id])


class Comments(models.Model):
    PRODUCT_STARS = [
        ('1', 'یک ستاره'),
        ('2', 'دو ستاره'),
        ('3', 'سه ستاره'),
        ('4', 'چهار ستاره'),
        ('5', 'پنج ستاره '),
    ]
    blog = models.ForeignKey(Blogs, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    star = models.CharField(max_length=100 ,null=True, choices=PRODUCT_STARS)
    text = models.TextField(null=True)
    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_modified = models.DateTimeField(auto_now=True)
    
    def get_absolute_url(self):
        return reverse('Blog_List_View', args=[self.id])



class Reply(models.Model):
    comment = models.ForeignKey(Comments, on_delete=models.CASCADE, related_name='reply')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(null=True)
    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_modified = models.DateTimeField(auto_now=True)

blog/forms.py
from django import forms
from .models import *
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['text' , 'star']


class ReplyForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['text']


class AddBlogForm(forms.ModelForm):
    class  Meta:
        model = Blogs
        fields = ['title', 'content', 'cover',  'is_active',]
        widgets = {
            'title' : forms.TextInput(attrs={'class':'form-control'}),
            'cover':forms.FileInput(attrs={'class':'btn-chang-avatar'}),
            # 'is_active': forms.CheckboxInput(attrs={'class':'form-control'}),
            'content': SummernoteWidget(), 
        }

blog/views.py
from django.shortcuts import render, redirect, reverse,get_object_or_404
from .models import Blogs, Comments
from django.views import generic
from django.urls import reverse_lazy
from .forms import CommentForm, ReplyForm, AddBlogForm
from accounts.models import User


def blog_list_view(request):
    user = User()
    blog_list = Blogs.objects.filter(is_active=True)
    return render(request, 'blog_list.html', context={'blogs':blog_list, 'user':user})

class BlogDetailView(generic.DetailView):
    model = Blogs
    template_name = 'blog_detail.html'
    context_object_name = 'blog'


class CommentCreatView(generic.View):
    model = Comments
    form = CommentForm
    template_name = 'comment/comment_create.html'

    def get(self, request, id):
        form = self.form()
        context = {'form': form}
        if request.user.is_authenticated:
            return render(request, self.template_name, context)
        return redirect(reverse('accounts:login'))

    def post(self, request, id):
        form = self.form(request.POST)
        blog = Blogs.objects.get(id=id)
        if form.is_valid():
            comment = self.model.objects.create(
                blog=blog,
                user= request.user,
                text=form.cleaned_data['text']
            )
            comment.save()
            return redirect('blog:blog_list')
        

        
def add_blog(request):
    if request.user.is_superuser:
        
        if request.method == "POST":
            print('ddd')
            form = AddBlogForm(request.POST, request.FILES)
            if form.is_valid():
                blog = Blogs.objects.create(
                    user = request.user,
                    title = form.data['title'],
                    content = form.data['content'],
                    is_active = True if form.data['is_active'] else False
                )
                blog.save()
                return redirect('accounts:profile_view')
            else:
                print(form.errors)
        return redirect('blog:blog_list')


def delete_blog_view(request, blog_id):
    if request.user.is_superuser:
        blog = Blogs.objects.get(id=blog_id)
        blog.delete()
        return redirect(reverse('accounts:profile_view'))
    return redirect('blog:blog_list')
    

def update_blog(request, pk):
    if request.user.is_superuser:
        blog = get_object_or_404(Blogs, id=pk)
        form = AddBlogForm(instance=blog)
        if request.method == "POST":
            form = AddBlogForm(request.POST , request.FILES ,instance=blog)
            if form.is_valid():
                form.save()
                return redirect(reverse('accounts:profile_view'))
            else:
                print(form.errors)
        return render(request, 'blog_update.html', context={'UPform':form, 'blog':blog})
            

blog/templates/blog_list.html
{% extends '_base.html' %}
{% load static %}
{% load jalali_tags %}

{% block page_title %}
    blog list
{% endblock %}

{% block link %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/respansive.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!--refrence carousel-->
    <link rel="stylesheet" href="{% static 'css/owlcarousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owlcarousel/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" /> -->
    <!--refrence lightbox video-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.0.47/jquery.fancybox.min.css"/>
{% endblock %}

{% block content %}
    <div class="content blog sidebar left-sidebar list">
        <section>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-9 py-5">
                        <div class="area-content-bySidebar ">
                            <nav aria-label="breadcrumb" class="mb-4">
                                <ol class="breadcrumb breadcrumb-singleProduct ">
                                    <li class="breadcrumb-item"><a href="#">خانه</a></li>
                                    <li class="breadcrumb-item"><a href="#">وبلاگ</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">وبلاگ لیستی</li>
                                </ol>
                            </nav>
                            <div class="title_site d-flex justify-content-start">
                                <h1>بلاگ</h1>
                            </div>
                            <div class="area-all-post mb-0 mb-md-3">
                                <div class="row">
                                    {% for blog in blogs %}
                                        <div class="col-12 mb-4 pb-2">
                                            <article class="card card-post d-flex flex-column flex-sm-row">
                                                <div class="hover01 column">
                                                    {% if blog.cover %}
                                                        <figure><a href="{% url 'blog:blog_detail' blog.id %}"
                                                                   class="card-img d-block"><img
                                                                src="{{ blog.cover.url }}" class="img-fluid h-100"/></a>
                                                        </figure>
                                                    {% else %}
                                                        <figure><a href="{% url 'blog:blog_detail' blog.id %}"
                                                                   class="card-img d-block"><img
                                                                src="{% static 'images\download (1).jfif' %}"
                                                                class="img-fluid h-100"/></a>
                                                        </figure>
                                                    {% endif %}
                                                </div>
                                                <!-- <div class="hover01"> <figure> <a href="#" class="card-img d-block"><img src="images/img-post1.jpg" class="img-fluid h-100" ></a></figure> </div> -->
                                                <div class="card-body">
                                                    <ul class="post-categories mb-3 mb-md-4">
                                                        <li><a href="#" rel="category tag">آموزش اhtml-css</a></li>
                                                        <li><a href="#" rel="category tag">آموزش طراحی سایت</a></li>
                                                        <li><a href="#" rel="category tag">آموزش طراحی سایت</a></li>
                                                    </ul>
                                                    <h2 class="title-post mb-2 mb-md-4"><a
                                                            href="{% url 'blog:blog_detail' blog.id %}">{{ blog.title }}
                                                    </a></h2>
                                                    <div class="porofile_author porofile_author-listPost  mb-4">
                                                        <a href="#" class="d-flex align-items-center">
                                                            <img class="imgAuthor"
                                                                 src="{% static 'images/castomer9787.jpg' %}"/>
                                                            <div class="porofileName">
                                                                <span>نویسنده:</span>
                                                                <span>{{ blog.user }}</span>
                                                            </div>
                                                        </a>
                                                    </div>
                                                    <div
                                                            class="area-infoPost d-flex justify-content-end align-items-center">
                                                        <a class="message-link " href="#" title="">
                                                            <span>{{ blog.comments.all |length }}</span>
                                                        </a>
                                                        <div class="border-divider"></div>
                                                        <a href="#" title="۸ اسفند, ۱۳۹۸" class="data-link">
                                                            {{ blog.datetime_created |to_jalali:'%Y/%m/%d' }}
                                                        </a>
                                                    </div>
                                                </div>
                                            </article>
                                        </div>

                                        </div>
                                        <div class="col-12 mb-4 pb-2">
                                            <article
                                                    class="card card-post card-post-conversely  d-flex flex-column flex-sm-row">
                                                <div class="card-body  order-2 order-sm-1">
                                                    <ul class="post-categories  mb-3 mb-md-4">
                                                        <li><a href="#" rel="category tag">آموزش اhtml-css</a></li>
                                                        <li><a href="#" rel="category tag">آموزش طراحی سایت</a></li>
                                                    </ul>
                                                    <h2 class="title-post mb-4"><a href="#">
                                                        {{ blog.title }}</a></h2>
                                                    <div class="porofile porofile_author  mb-4">
                                                        <a href="#" class="d-flex align-items-center">
                                                            <img class="imgPorofile"
                                                                 src="{% static 'images/castomer9787.jpg' %}"/>
                                                            <div class="porofileName">
                                                                <span>نویسنده:</span>
                                                                <span>{{ blog.user }}</span>
                                                            </div>
                                                        </a>
                                                    </div>
                                                    <div
                                                            class="area-infoPost d-flex justify-content-end align-items-center">
                                                        <a class="message-link " href="#" title="">
                                                            <span>{{ blog.comments.all |length }}</span>
                                                        </a>
                                                        <div class="border-divider"></div>
                                                        <a href="#" title="۸ اسفند, ۱۳۹۸" class="data-link">
                                                            {{ blog.datetime_created |to_jalali:'%Y/%m/%d' }}
                                                        </a>
                                                    </div>
                                                </div>
                                                <div class="hover01 column order-1  order-sm-2">
                                                    <figure><a href="#" class="card-img d-block"><img
                                                            src="{% static 'images/img-post6.jpg' %}"
                                                            class="img-fluid h-100"/></a>
                                                    </figure>
                                                </div>
                                            </article>
                                        </div>
                                    {% endfor %}
                            </div>
                        </div>
                        <div
                                class="area-pageination-shop  d-flex  flex-column flex-md-row justify-content-between align-items-center mb-0 mb-md-3">
                            <ul class="pagination pagination-lg d-flex justify-content-center order-2 order-md-1">
                                <li class="page-item ms-2"><a class="page-link" href="#" aria-label="Previous"><i
                                        class="fas fa-chevron-right"></i></a></li>
                                <li class="page-item"><a class="page-link" href="#">1</a></li>
                                <li class="page-item active"><a class="page-link " href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item"><a class="page-link" href="#">4</a></li>
                                <li class="page-item ">...</li>
                                <li class="page-item"><a class="page-link" href="#">10</a></li>
                                <li class="page-item me-2"><a class="page-link" href="#" aria-label="Next"><i
                                        class="fas fa-chevron-left"></i></a></li>
                            </ul>
                            <div
                                    class="box-select-NumberProduct-the-page d-flex align-items-center justify-content-center justify-content-md-end mb-4 mb-md-0 pb-2 pb-md-0  order-1 order-md-2">
                                <label class="lable-select-NumberProduct-the-page"
                                       for="select-NumberProduct-the-page">نمایش </label>
                                <select class="form-select custom-select mx-3" id="select-NumberProduct-the-page"
                                        aria-label="Default select example">
                                    <option selected>12</option>
                                    <option value="1">24</option>
                                    <option value="2">36</option>
                                    <option value="3">48</option>
                                </select>
                                <span>محصول در صفحه</span>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
    </div>
    </section>
    </div>
{% endblock %}

blog/templates/blog_update.html
{% extends '_base.html' %}
{% load static %}
{% load jalali_tags %}

{% block page_title %}
    My Account
{% endblock %}

{% block link %}
    <link rel="stylesheet" href="{% static 'css/respansive.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!--refrence carousel-->
    <link rel="stylesheet" href="{% static 'css/owlcarousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owlcarousel/owl.theme.default.min.css' %}">
    <!--refrence carousel-->
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" /> -->
    <!--refrence lightbox video-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.0.47/jquery.fancybox.min.css"/>
    <link rel="stylesheet" href="{% static 'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' %}">
{% endblock %}

{% block content %}
    <form action='{% url 'blog:update_blog' blog.id %}' method="POST" enctype="multipart/form-data">
        {{ UPform.title }}
        {{ UPform.content }}
        <div class="row">
            <div class="form-check">
                <label class="form-check-label" for="gridCheck">
                    وبلاگ موجود است؟
                </label>
                {{ UPform.is_active }}

            </div>
        </div>
        {% csrf_token %}
        <div class="area-btn-save">
            <button type="submit" class="btn btn-5"> ذخیره تغییرات
            </button>
        </div>

    </form>


{% endblock %}