Home/urls.py
from django.urls import path
from .views import home_view

app_name = 'Home'
urlpatterns = [
    path('', home_view, name='HomeView'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('blog', include('blog.urls')),
    path('', include('Home.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('favorite/', include('favorite.urls')),
    path('contact/', include('contact.urls')),
    path('ticket/', include('tickets.uels')),


    # path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import product_list, product_detail, search_product,add_product, delete_product, update_product, add_category, category_list
app_name = 'products'


urlpatterns = [
    path('', product_list, name='product_list'),
    path('result/<str:category>', product_list, name='product_category'),
    path('<int:pk>', product_detail, name='product_detail'),
    path('search', search_product, name='search_product'),
    path('add_product', add_product, name='add_product'),
    path('add_category', add_category, name='add_category'),

    path('<int:pk>/delete', delete_product, name='delete_product'),
    path('<int:pk>/update', update_product, name='update_product'),
    # path('product_filter_view', product_filter_view, name='product_filter_view'),
    path('category_list', category_list, name='category_list'),





 


    

] 

products/models.py
from collections.abc import Iterable
from django.db import models
from django.db import models
from django.urls import reverse
from accounts.models import User



class Category(models.Model):
    name = models.CharField(max_length=100)
    # products = models.ForeignKey(Products, on_delete=models.CASCADE, null=True)
    def __str__(self):
        return self.name

class Products(models.Model):
    PRODUCT_STARS = [
        ('1', 'یک ستاره'),
        ('2', 'دو ستاره'),
        ('3', 'سه ستاره'),
        ('4', 'چهار ستاره'),
        ('5', 'پنج ستاره '),
    ]
    
    title = models.CharField(max_length=100)
    content = models.TextField(null=True)
    cover = models.ImageField(upload_to='products/', null=True)
    star = models.CharField(max_length=100 ,null=True, choices=PRODUCT_STARS)
    price = models.PositiveBigIntegerField(default=0)
    second_price = models.PositiveBigIntegerField(default=0)
    inventory = models.IntegerField(default=0, null=True)
    active = models.BooleanField(default=True)
    discouont = models.PositiveIntegerField(default=0, null=True)
    Datetime_create = models.DateTimeField(auto_now_add=True)
    Datetime_modified = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        self.second_price =  int(self.price - (self.price * (self.discouont/100)))
        return super(Products, self).save(*args, **kwargs)
    


    
    


class Comment(models.Model):
    PRODUCT_STARS = [
        ('1', 'یک ستاره'),
        ('2', 'دو ستاره'),
        ('3', 'سه ستاره'),
        ('4', 'چهار ستاره'),
        ('5', 'پنج ستاره '),
    ]
    product = models.ForeignKey(Products, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    star = models.CharField(max_length=100 ,null=True, choices=PRODUCT_STARS)
    text = models.TextField(null=True)
    datetime_created = models.DateTimeField(auto_now_add=True)
    datetime_modified = models.DateTimeField(auto_now=True)

products/forms.py
from .models import Comment, Products, Category
from django import forms
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text' , 'star']



class AddProductForm(forms.ModelForm):
    class  Meta:
        model = Products
        fields = ['title', 'content', 'cover', 'star', 'price', 'active', 'discouont', 'inventory', 'category']
        widgets = {
            'title' : forms.TextInput(attrs={'class':'form-control'}),
            'star' : forms.Select(attrs={'class':'form-select custom-select'}),
            'category' : forms.Select(attrs={'class':'form-select custom-select'}),

            # 'active': forms.CheckboxInput(attrs={'class':'form-check-input'}),
            'cover':forms.FileInput(attrs={'class':'btn-chang-avatar'}),
            'price': forms.TextInput(attrs={'class':'form-control'}),
            'discouont': forms.TextInput(attrs={'class':'form-control'}),
            'price': forms.TextInput(attrs={'class':'form-control'}),
            'content':SummernoteWidget(),

            # 'content': forms.TextInput(attrs={'class':'form-control'}),
            
        }


class AddCategory(forms.ModelForm):
    class  Meta:
        model = Category
        fields = ['name']
        widgets = {
            'name' : forms.TextInput(attrs={'class':'form-control'}),             
        }

        

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404, get_list_or_404
from .models import Products, Comment, Category
from django.views import generic
from .forms import CommentForm, AddProductForm, AddCategory
from cart.forms import CartForm
from django.core.paginator import Paginator
from .filters import ProductFilter


def product_list(request, category=None):
    if category:
        categoryobj = Category.objects.get(name=category)
        product = get_list_or_404(Products, category=categoryobj)
        paginator = Paginator(product, 2)
        page = request.GET.get('page', 1)
        page_obj = paginator.get_page('page')

    else:
        category = Category.objects.all()
        product = Products.objects.filter(active=True)
        filter = ProductFilter(request.GET, queryset=product)
        paginator = Paginator(filter.qs, 2)
        page = request.GET.get('page', 1)
        page_obj = paginator.get_page(page)
        print(paginator.page(1))

    categorys = []
    for item in Category.objects.all():
        category_name = {}
        length = len(Products.objects.filter(category__name=item.name))
        category_name["name"] = item.name
        category_name["length"] = length
        categorys.append(category_name)

    return render(request, 'product_list.html', context={"page_obj": page_obj, 'category': categorys})


def product_detail(request, pk):
    cart_form = CartForm()
    product = Products.objects.get(id=pk)

    form = CommentForm()
    if request.method == "POST":
        form = CommentForm(request.POST)

        comment = Comment.objects.create(
            product=product,
            user=request.user,
            text=form.data['text'],
            star=form.data['star']

        )
        comment.save()
        return redirect(reverse('products:product_list'))

    return render(request, 'product_detail.html',
                  context={'product': product, 'form': form, 'cart_form': cart_form, })


def search_product(request):
    if request.method == "POST":
        title = request.POST['search']
        product = Products.objects.filter(title__contains=title)
        if product.exists():

            return render(request, 'product_list.html', context={'page_obj': product})
        else:
            return render(request, 'search_not_found.html')


def add_product(request):
    if request.user.is_superuser:

        if request.method == "POST":
            form = AddProductForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                return redirect('accounts:profile_view')
            else:
                print(form.errors)
        return redirect('blog:blog_list')


def add_category(request):
    if request.user.is_superuser:
        if request.method == "POST":
            form = AddCategory(request.POST)
            if form.is_valid():
                form.save()
                return redirect('accounts:profile_view')
            else:
                print(form.errors)
        return redirect('blog:blog_list')


def delete_product(request, pk):
    if request.user.is_superuser:
        product = Products.objects.get(id=pk)
        product.delete()
        return redirect(reverse('accounts:profile_view'))
    return redirect('blog:blog_list')


def update_product(request, pk):
    if request.user.is_superuser:
        product = get_object_or_404(Products, id=pk)
        form = AddProductForm(instance=product)
        if request.method == "POST":
            print('aaa')

            form = AddProductForm(request.POST, request.FILES, instance=product)
            if form.is_valid():
                print('qqqqq')
                form.save()
                return redirect(reverse('accounts:profile_view'))
            else:
                print(form.errors)
        return render(request, 'product_update.html', context={'UPform': form, 'product': product})


def category_list(request):
    category = Category.objects.all()
    return render(request, 'category.html', context={'categorys': category})

products/templates/category.html
{% extends '_base.html' %}
{% load static %}
{% load jalali_tags %}

{% block page_title %}
    product list
{% endblock %}

{% block link %}
    <link rel="stylesheet" href="{% static 'css/respansive.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!--refrence carousel-->
    <link rel="stylesheet" href="{% static 'css/owlcarousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owlcarousel/owl.theme.default.min.css' %}">
    <!--refrence carousel-->
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/category.CSS' %}">

{% endblock %}



{% block content %}
    {% for category in categorys %}
        <div class='category_list'>
            <a class="category_list--a" href="{%  url 'products:product_category' category.name %}">{{ category.name }}</a>

        </div>

    {% endfor %}
{% endblock %}

products/templates/product_update.html
{% extends '_base.html' %}
{% load static %}
{% load jalali_tags %}

{% block page_title %}
    My Account
{% endblock %}

{% block link %}
    <link rel="stylesheet" href="{% static 'css/respansive.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!--refrence carousel-->
    <link rel="stylesheet" href="{% static 'css/owlcarousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owlcarousel/owl.theme.default.min.css' %}">
    <!--refrence carousel-->
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" /> -->
    <!--refrence lightbox video-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.0.47/jquery.fancybox.min.css"/>
    <link rel="stylesheet" href="{% static 'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' %}">
{% endblock %}

{% block content %}
    <form action='{% url 'products:update_product' product.id %}' method="POST" enctype="multipart/form-data">
        <div class="avatar-user d-flex flex-column justify-content-center align-items-center mb-4">
                <img class="img-avatar-user" src="{{ product.cover.url }}">
            
            


        </div>
        {{ UPform.title }}
        {{ UPform.content }}
        {{ UPform.price }}
        {{ UPform.star }}
        {{ UPform.cover }}
        {{ UPform.active }}
        {{ UPform.discouont }}
         موجودی : {{ UPform.inventory }}
        {{ UPform.category }}


        {% csrf_token %}
        <div class="area-btn-save">
            <button type="submit" class="btn btn-5"> ذخیره تغییرات
                    </button>
        </div>

    </form>


{% endblock %}

products/templates/search_not_found.html
{% extends '_base.html' %}
{% load static %}
{% load jalali_tags %}

{% block page_title%}
   product list 
{% endblock %}

{% block link %}
    <link rel="stylesheet" href="{% static 'css/respansive.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!--refrence carousel-->
    <link rel="stylesheet" href="{% static 'css/owlcarousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owlcarousel/owl.theme.default.min.css' %}">
    <!--refrence carousel-->
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
{%endblock%}

{% block content%}
   <div class="content">
        <div class="container ">
            <div class="row">
                <div class="area-content-P404 col-12 d-flex justify-content-center flex-column align-items-center py-5">
                    <h1 class="mb-3 d-flex justify-content-center align-items-center flex-column">
                        <img class="img-fluid" src="{% static 'images/img404.svg' %}" />
                        <span class="text-center d-inline-block text-danger mt-2">خطای کد: 404</span>
                    </h1>
                    <h2 class="title404 mb-2">اوه محصول پیدا نشد!</h2>
                    <p class="mb-4"> به نظر می رسد ما نمی توانیم محصول مورد نظر را پیدا کنیم.</p>
                    <div class=" mb-4 pb-2">
                        <a href="{% url 'Home:HomeView' %}"
                            class="ml-4 button-outline button-outline-P404"> برگشت به صفحه اصلی</a>
                    </div>
                    <div class="area-search404  w-100 d-flex justify-content-center ">
                        <form action='{% url 'products:search_product'%}' class="search-form d-flex position-relative" action="" method="post">
                            <input type="text" class="form-control input_search " name="search" id='search' value="" placeholder="جستجو">
                            {% csrf_token %}
                            <button type="submit">
                                <svg width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor"
                                    xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd"
                                        d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z">
                                    </path>
                                    <path fill-rule="evenodd"
                                        d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z">
                                    </path>
                                </svg>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}