Home/urls.py
from django.urls import path
from .views import home_view

app_name = 'Home'
urlpatterns = [
    path('', home_view, name='HomeView'),

]

cart/urls.py
from django.urls import path
from .views import add_to_cart, cart_detail, remove_from_cart, chetout

app_name = 'cart'

urlpatterns = [
    path('AddToCart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('cartdetail/', cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', remove_from_cart, name='remove_from_cart'),
    path('chetout', chetout, name='chetout'),


] 

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('blog', include('blog.urls')),
    path('', include('Home.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('favorite/', include('favorite.urls')),
    path('contact/', include('contact.urls')),
    path('ticket/', include('tickets.uels')),


    # path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import product_list, product_detail, search_product,add_product, delete_product, update_product, add_category, category_list
app_name = 'products'


urlpatterns = [
    path('', product_list, name='product_list'),
    path('result/<str:category>', product_list, name='product_category'),
    path('<int:pk>', product_detail, name='product_detail'),
    path('search', search_product, name='search_product'),
    path('add_product', add_product, name='add_product'),
    path('add_category', add_category, name='add_category'),

    path('<int:pk>/delete', delete_product, name='delete_product'),
    path('<int:pk>/update', update_product, name='update_product'),
    # path('product_filter_view', product_filter_view, name='product_filter_view'),
    path('category_list', category_list, name='category_list'),





 


    

] 

cart/models.py
from django.db import models
from accounts.models import User
from products.models import Products
import random
import string



def generate_unic_code():
    cod_length = 6
    characters = string.ascii_letters + string.digits

    while(True):
        code = ''.join(random.choice(characters) for _ in range(cod_length)) 
        
        if not Order.objects.filter(code=code).exists():
            return code
            


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    products = models.ForeignKey(Products, on_delete=models.CASCADE)
    count = models.IntegerField(default=0)
    end_price = models.CharField(max_length=100, null=True, default=0)

    
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    first_name = models.CharField(max_length=100)
    last_name= models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    post_id = models.CharField(max_length=10, null=True)
    description = models.CharField(max_length=100, blank=True)
    totla_price = models.CharField(max_length=100, default=0)
    code = models.CharField(max_length=6, unique=True, default=generate_unic_code, null=True)


class OrderItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    product_price = models.DecimalField(max_digits=10, decimal_places=0)
    product_count = models.PositiveIntegerField()
    product_cost = models.DecimalField(max_digits=10, decimal_places=0)



    

cart/forms.py
from django import forms
from .models import Order

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'city', 'address', 'description', 'post_id']
        widgets = {
            'user' : forms.TextInput(attrs={'class':'form-control'}),
            'date' : forms.TextInput(attrs={'class':'form-control'}),
            'first_name' : forms.TextInput(attrs={'class':'form-control'}),
            'last_name' : forms.TextInput(attrs={'class':'form-control'}),
            'city' : forms.TextInput(attrs={'class':'form-control'}),
            'address' : forms.TextInput(attrs={'class':'form-control'}),
            'description' : forms.TextInput(attrs={'class':'form-control'}),
            'post_id' : forms.TextInput(attrs={'class':'form-control'}),

        }

class CartForm(forms.Form):
    product_count = forms.IntegerField()

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from products.models import Products
from .models import Cart, Order, OrderItem
from .forms import CartForm, OrderForm


def add_to_cart(request, product_id):
    form = CartForm(request.POST)
    
    product = Products.objects.get(id=product_id)
    if Cart.objects.filter(user=request.user, products=product).exists():
        cart = Cart.objects.get(user=request.user, products=product)
        if form.is_valid():
            cart.count = cart.count + int(form.data['product_count'])
            cart.save()
            cart.end_price = str(cart.count * product.second_price)
        else:
            cart.count += 1
            cart.end_price = str(int(cart.end_price) + product.second_price)
        
        cart.save()
    else:
        try:
            count = form.data['product_count']
        except:
            count = 1
        cart = Cart.objects.create(
            user=request.user, 
            products=product,
            count = count,
            end_price = str(product.second_price * int(count)), 
        )
        cart.save()
    return redirect('cart:cart_detail' )

def cart_detail(request):
    cart = Cart.objects.filter(user=request.user)
    total_price = 0
    for i in cart:
        total_price = total_price + i.products.second_price * i.count

    return render(request,  'cart.html', context={'cart':cart, "total_price":total_price})

def remove_from_cart(request, product_id):
    product = Products.objects.get(id=product_id)
    cart = get_object_or_404(Cart, products=product, user=request.user)
    cart.delete()
    return redirect('cart:cart_detail')

def chetout(request):
    cart = Cart.objects.filter(user=request.user)
    form = OrderForm()

    
    if request.method == "POST":
        form = OrderForm(request.POST)

        total_price = 0
        for i in cart:
            total_price = total_price + i.products.second_price * i.count
        order = Order.objects.create(
            user = request.user,
            first_name = form.data['first_name'],
            last_name = form.data['last_name'],
            city = form.data['city'],
            # description = form.data['description'],
            post_id = form.data['post_id'],
            totla_price = total_price
        )
        order.save()
        for item in cart:
            product = Products.objects.get(id=item.products.id)
            orderItem = OrderItem.objects.create(
                user = request.user,
                order = order,
                product = product,
                product_price = item.products.price,
                product_count = item.count,
                product_cost = item.end_price

            )
            orderItem.save()
            product.inventory -= item.count
            product.save()
            product_cart = Cart.objects.get(user=request.user, products=product)
            product_cart.delete()
            return render(request, 'compelete_order.html')
    return render(request, 'chekout.html', context={'cart':cart, 'formOrder':form})

cart/templates/cart.html
{% extends '_base.html' %}
{% load static %}
{% load jalali_tags %}

{% block page_title %}
    سبد خرید
{% endblock %}

{% block link %}
    <link rel="stylesheet" href="{% static 'css/respansive.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!--refrence carousel-->
    <link rel="stylesheet" href="{% static 'css/owlcarousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owlcarousel/owl.theme.default.min.css' %}">
    <!--refrence carousel-->
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">





{% endblock %}

{% block content %}
    <body class="bgSecondary">
    <div class="bg-close">
    </div>

    <div class="content-cart pb-4 pb-xl-5 pt-5">
        <section>
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <nav aria-label="breadcrumb" class="mb-5">
                            <ol class="breadcrumb ">
                                <li class="breadcrumb-item"><a href="#">خانه</a></li>
                                <li class="breadcrumb-item active" aria-current="page"><a href="#">سبد خرید</a></li>
                            </ol>
                        </nav>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12 col-lg-9">
                        <div class="area-content-cart">

                            <div class="table-cart-shop ">
                                <div class="d-none d-md-block">
                                    <div
                                            class="area-title-table-cart box-table-cart  box-cart d-flex align-items-center">
                                        <div class="item-table-cart product-cart">محصول</div>
                                        <div class="item-table-cart product-count">تعداد</div>
                                        <div class="item-table-cart product-price">قیمت</div>
                                        <div class="item-table-cart total">جمع جزء</div>
                                    </div>
                                </div>
                                {% for item in cart %}
                                    <div
                                            class="area-content-table-cart box-table-cart box-cart d-flex flex-column flex-md-row align-items-center  ">
                                        <div
                                                class="item-table-cart product-cart  d-flex flex-column flex-md-row align-items-center">
                                            <a href="{% url 'cart:remove_from_cart' item.products.id %}" class="btn btn-remove-cart btn-remove">
                                                <i class="fas fa-trash-alt"></i>
                                                <span class="tooltip-site">حذف</span>
                                            </a>
                                            <div class="img-product-cart mb-4 mb-md-0 mx-1">
                                                <a href="{% url 'products:product_detail' item.products.id %}"><img src="{{ item.products.cover.url }}"></a>
                                            </div>
                                            <div class="title-product-cart mb-4 mb-md-0 ms-0 ms-md-2">
                                                <a href="{% url 'products:product_detail' item.products.id %}">
                                                    <h3>{{item.products.title}}</h3>
                                                </a>
                                            </div>
                                        </div>
                                        <div class="item-table-cart product-count  mb-4 mb-md-0">
                                            <div
                                                    class="input-number-wrapper d-flex justify-content-center align-items-center">
                                                <span class="quanti-invitati-op increase">+</span>
                                                <input class="input-number-custtom" type="text"
                                                       value="{{ item.count }}"/>
                                                <span class="quanti-invitati-op decrease">-</span>
                                            </div>
                                        </div>
                                        <div class="item-table-cart product-price ">
                                            {{ item.end_price }} تومان
                                        </div>
                                        <div class="item-table-cart total ">
                                            {{ item.products.second_price }} تومان
                                        </div>
                                    </div>
                                {% endfor %}

                            </div>
                            <div
                                    class="box-coupon-cart box-cart d-flex flex-column flex-md-row justify-content-between align-items-center">
                                <div
                                        class="area-coupon d-flex justify-content-between  justify-content-md-start align-items-center mb-4 mb-md-0 w-100">
                                    <form>
                                        <div class="form-group">
                                            <input type="text" class="form-control" id="input-coupon"
                                                   placeholder="کد تخفیف">
                                        </div>
                                    </form>

                                    <button type="submit" class="btn btn-5"> اعمال کوپن</button>
                                </div>
                                <div class="area-btn-update">
                                    <button type="submit" class="btn btn-5">بروزرسانی سبد خرید</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-lg-3">
                        <div class="area-checkout-cart box-cart">
                            <div class="cart-subtotal d-flex justify-content-between align-items-center ">
                                <span>مجموع</span>

                                <span class="subtotal">{{total_price}} تومان</span>
                            </div>
                            <div class="amount-of-payable  d-flex justify-content-between align-items-center mt-5 mb-4">
                                <span> مجموع سبد خرید</span>

                                <span class="payable">{{total_price}} تومان</span>
                            </div>
                            <div class="area-btn-checkout ">
                                <a href='{% url 'cart:chetout' %}'  type="submit" class="btn btn-5">ادامه جهت تسویه حساب</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    </body>
{% endblock %}

cart/templates/compelete_order.html
{% extends '_base.html' %}
{% load static %}
{% load jalali_tags %}

{% block page_title%}
   product list 
{% endblock %}

{% block link %}
    <link rel="stylesheet" href="{% static 'css/respansive.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!--refrence carousel-->
    <link rel="stylesheet" href="{% static 'css/owlcarousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owlcarousel/owl.theme.default.min.css' %}">
    <!--refrence carousel-->
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
{%endblock%}

{% block content%}
   <div class="content">
        <div class="container ">
            <div class="row">
                <div class="area-content-P404 col-12 d-flex justify-content-center flex-column align-items-center py-5">
                    <h1 class="mb-3 d-flex justify-content-center align-items-center flex-column">
                        <img class="img-fluid" src="{% static 'images/img404.svg' %}" />
                        <span class="text-center d-inline-block text-danger mt-2"></span>
                    </h1>
                    <h2 class="title404 mb-2">خرید شما با موفقیت ثبت شد   !</h2>
                    
                   
                </div>
            </div>
        </div>
    </div>

{% endblock %}