Home/urls.py
from django.urls import path
from .views import home_view

app_name = 'Home'
urlpatterns = [
    path('', home_view, name='HomeView'),

]

cart/urls.py
from django.urls import path
from .views import add_to_cart, cart_detail, remove_from_cart, chetout

app_name = 'cart'

urlpatterns = [
    path('AddToCart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('cartdetail/', cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', remove_from_cart, name='remove_from_cart'),
    path('chetout', chetout, name='chetout'),


] 

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('blog', include('blog.urls')),
    path('', include('Home.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('favorite/', include('favorite.urls')),
    path('contact/', include('contact.urls')),
    path('ticket/', include('tickets.uels')),


    # path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

favorite/urls.py
from django.urls import path
from .views import add_to_favorite, favorite_items, remove_from_wishlist

app_name = 'favorite'


urlpatterns = [
    path('<int:product_id>/add', add_to_favorite, name='add_to_favorite'),
    path('wishlist', favorite_items, name='wishlist'),
    path('remove/<int:product_id>/', remove_from_wishlist, name='remove_from_wishlit'),
    path('remove/', remove_from_wishlist, name='remove_all_wishlit'),




] 

products/urls.py
from django.urls import path
from .views import product_list, product_detail, search_product,add_product, delete_product, update_product, add_category, category_list
app_name = 'products'


urlpatterns = [
    path('', product_list, name='product_list'),
    path('result/<str:category>', product_list, name='product_category'),
    path('<int:pk>', product_detail, name='product_detail'),
    path('search', search_product, name='search_product'),
    path('add_product', add_product, name='add_product'),
    path('add_category', add_category, name='add_category'),

    path('<int:pk>/delete', delete_product, name='delete_product'),
    path('<int:pk>/update', update_product, name='update_product'),
    # path('product_filter_view', product_filter_view, name='product_filter_view'),
    path('category_list', category_list, name='category_list'),





 


    

] 

favorite/models.py
from django.db import models
from accounts.models import User
from products.models import Products


class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)

favorite/views.py
from django.shortcuts import render ,redirect, get_object_or_404, reverse
from .models import Favorite
from products.models import Products



def add_to_favorite(request, product_id):

    
    product = Products.objects.get(id=product_id)
    if Favorite.objects.filter(user=request.user, product=product).exists():
        pass
    else:
        favorite = Favorite.objects.create(
            user = request.user,
            product=product,
        )
        favorite.save()
    return redirect('products:product_list')



def favorite_items(request):
    favorite = Favorite.objects.filter(user=request.user)

    return render(request, 'wish_list.html', context={'favorite':favorite})



def remove_from_wishlist(request, product_id=None):
    if product_id:
        product = Products.objects.get(id=product_id)
        print(request.user)

        favorite = Favorite.objects.get(product=product ,user=request.user)
        favorite.delete()

        return redirect(reverse('favorite:wishlist'))
    else:
        favorite = Favorite.objects.filter(user=request.user)
        for item in favorite:
            favorite_obj = Favorite.objects.get(id=item.id)
            favorite_obj.delete()

        return redirect(reverse('accounts:profile_view')) 
        

favorite/templates/wish_list.html
{% extends '_base.html' %}
{% load static %}
{% load jalali_tags %}

{% block page_title %}
    wishlist
{% endblock %}

{% block link %}
    <link rel="stylesheet" href="{% static 'css/respansive.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!--refrence carousel-->
    <link rel="stylesheet" href="{% static 'css/owlcarousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owlcarousel/owl.theme.default.min.css' %}">
    <!--refrence carousel-->
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
{% endblock %}

{% block content %}
<div class="content-wishlist pb-4 pb-xl-5 pt-5">
    <section>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav aria-label="breadcrumb" class="mb-5">
                        <ol class="breadcrumb ">
                            <li class="breadcrumb-item"><a href="#">خانه</a></li>
                            <li class="breadcrumb-item active" aria-current="page">علاقه مندی ها</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="area-content-wishlist">
                        <table class="table table-wishlist">
                            <thead>
                            <tr>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col">محصول</th>
                                <th scope="col">قیمت</th>
                                <th scope="col">وضعیت</th>
                                <th scope="col"></th>
                            </tr>
                            </thead>
                            <tbody>

                            {% for item in favorite %}
                                <tr>
                                <th scope="row"><a href="{% url 'favorite:remove_from_wishlit' item.product.id %}"
                                                   class="btn btn-remove-wishlist btn-remove">
                                    <i class="fas fa-trash-alt"></i>
                                    <span class="tooltip-site">حذف</span>
                                </a></th>
                                <td><a href="{% url 'products:product_detail' item.product.id %}"><img
                                        src="{{ item.product.cover.url }}"/></a></td>
                                <td><a href="#" class="name-product-wishlist">
                                    <h3> {{ item.product.title }}</h3>
                                </a>
                                </td>
                                <td>{{ item.product.price }} تومان</td>
                                {% if item.product.active %}
                                    <td>
                                                <span class="status-product stok">
                                                    موجود
                                                </span>
                                    </td>
                                {% else %}
                                    <td>
                                                <span class="status-product  not-stok">
                                                    ناموجود
                                                </span>
                                    </td>
                            {% endif %}

                            <td>
                                <div class="area-btn-addtocart-wishlist">
                                    <a href='{% url 'cart:add_to_cart' item.product.id %}' class="btn btn-5"> افزودن به سبد خرید<i
                                            class="fal fa-cart-arrow-down me-2"></i></a>
                                </div>
                            </td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        <!-- WISHLIST MOBILE -->
                        <ul class="table-wishlist responsive-mobile d-block d-md-none">
                            <li>
                                <div
                                        class="product-wishlist responsive-mobile bg-white d-flex align-items-center  mb-4">
                                    <div class="product-thumbnail ms-2 ms-md-3"><a href="#"><img
                                            src="images/hansfari78.jpg"/></a>
                                    </div>
                                    <div class="product-details-responsive-mobile">
                                        <div class="product-name">
                                            <h3>
                                                <a href="#" class="name-product-wishlist"> هدفون بی سیم</a>
                                            </h3>
                                        </div>

                                        <div class="Price-amount">250000 تومان</div>
                                    </div>

                                </div>

                                <div class="additional-info-wishlist responsive-mobile d-flex align-items-center">

                                        <span class="status-product stok ms-3">
                                            موجود
                                        </span>

                                    <div class="area-btn-addtocart-wishlist ms-3">
                                        <button type="submit" class="btn btn-5"> افزودن به سبد خرید<i
                                                class="fal fa-cart-arrow-down me-2"></i></button>
                                    </div>

                                    <a href="#" class="btn btn-remove-wishlist btn-remove">
                                        <i class="fas fa-trash-alt"></i>
                                        <span class="tooltip-site">حذف</span>
                                    </a>
                                </div>

                            </li>
                            <li>
                                <div
                                        class="product-wishlist responsive-mobile bg-white d-flex align-items-center  mb-4">
                                    <div class="product-thumbnail ms-2 ms-md-3"><a href="#"><img
                                            src="images/kolah757.jpg"/></a>
                                    </div>

                                    <div class="product-details-responsive-mobile">
                                        <div class="product-name">
                                            <h3>
                                                <a href="#" class="name-product-wishlist"> کلاه آفتابگیر</a>
                                            </h3>
                                        </div>

                                        <div class="Price-amount">80000 تومان</div>
                                    </div>
                                </div>
                                <div class="additional-info-wishlist responsive-mobile d-flex align-items-center">

                                        <span class="status-product  not-stok ms-3">
                                            ناموجود
                                        </span>
                                    <div class="area-btn-addtocart-wishlist ms-3">
                                        <button type="submit" class="btn btn-5"> افزودن به سبد خرید<i
                                                class="fal fa-cart-arrow-down me-2"></i></button>
                                    </div>

                                    <a href="#" class="btn btn-remove-wishlist btn-remove">
                                        <i class="fas fa-trash-alt"></i>
                                        <span class="tooltip-site">حذف</span>
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </section>
</div>
{% endblock %}